def display_response(response, target):
    print("========== Result ==========")
    print(f"Target URL: {target}")
    print(f"Final URL: {response.url}")
    print(f"Status Code: {response.status_code}")
    print("\n========== Response ==========")
    print(f"Content-Type: {response.headers.get("content-type")}")
    print(f"Content-Length: {response.headers.get("content-length")}")
    print(f"Server: {response.headers.get("server")}")
    print(f"Cache-Control: {response.headers.get("cache-control")}")
    print(f"Content-Security-Policy: {response.headers.get("content-security-policy")}")
    print(f"X-Frame-Options: {response.headers.get("x-frame-options")}")
    print(f"Set-Cookie: {response.headers.get("set-cookie")}")
    print(f"Data: {response.headers.get("data")}")
